version: '2.1'
orbs:
  gradle: circleci/gradle@3.0.0
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0
jobs:
  node_build_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/frontend/frontend-app
      - run:
          command: |
            cd frontend/frontend-app
            npm run build
          name: Build app
  node_docker:
    executor: docker/machine
    steps:
        - checkout
        - docker/check
        - docker/publish:
            path: frontend/frontend-app/
            image: neeleshrav/knowledgespacesui
workflows:
  kotlin-build-test:
    jobs:
      - gradle/test:
          app_src_directory: GPTBackendServer/
      - gradle/run:
          app_src_directory: GPTBackendServer/
          command: jib
  node-build-test:
    jobs:
      - node_build_test
      - node_docker

