apiVersion: v1
kind: Service
metadata:
  name: circle-service
  labels:
    app: circle
spec:
  ports:
    - port: 2323
  selector:
    app: ci-deploy
    tier: backend
  type: LoadBalancer
  loadBalancerIP: "34.159.146.112"